spring.application.name=TravelAgency

# --- MAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=isa595976@gmail.com
spring.mail.password=bbfticdseqamivan
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- POSTGRES ---
spring.datasource.url=jdbc:postgresql://localhost:5432/iis_database
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=super
spring.h2.console.enabled=true

# --- JPA / HIBERNATE ---
# Ako ?eli? da se tabele bri?u i kreiraju pri svakom pokretanju:
# spring.jpa.hibernate.ddl-auto=create-drop
# Ako ?eli? da ti baza ostane i samo da se nadogra?uje:
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- OSTALO ---
spring.jackson.serialization.fail-on-empty-beans=false

# umesto deprecated spring.datasource.initialization-mode
spring.sql.init.mode=always

jwt.secret=JhU2&vL9@hQ#8!DxlZGhRtX#G@lEkV^jUoF0Hp$QlY3rQWm!
jwt.expiration=86400000

# Path to the directory where pictures are stored
pictures.directory=src/main/resources/static/pictures/
